const translations = {
  en: {
    welcomeShort: "Welcome to RwandaConnect – your guide to all events in Rwanda!",
    home: "Home",
    cities: "Cities",
    map: "Map",
    login: "Login / Sign Up",
    city1: "Kigali", 
    desc1: "Kigali is the capital city, full of life, activities, and culture.",
    city2: "Nyagatare", 
    desc2: "An area known for its warm weather and growing event scene.",
    city3: "Rubavu", 
    desc3: "Beautiful lakeside city, perfect for music, sports and beach events.",
    city4: "Rwamagana", 
    desc4: "A quiet and friendly city with lots of family activities and community gatherings.",
    city5: "Rusizi", 
    desc5: "A place famous for its beautiful nature and peaceful air.",
    city6: "Huye", 
    desc6: "Home of history and cultural festivals.",
    city7: "Musanze", 
    desc7: "The gateway to the volcanoes, buzzing with tourism and events.",
    city8: "Bugesera", 
    desc8: "An upcoming city with a growing number of local activities & a special history.",
    viewMap: "View Map",
    signupAsHost: "Sign Up as Host",
    signupAsGoer: "Sign Up as Goer",
    alreadyAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    signupFree: "Sign up for free!",
    or: "or",
    fieldRequired: "This field is required",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    username: "Username",
    organizationName: "Organization Name",
    interests: "Interests",
    hostingType: "What type of events do you host?",
    loginAsHost: "Login as Event Host",
    loginAsGoer: "Login as Event Goer",
    chooseRole: "Choose your role",
    createAccount: "Create Account",
    signIn: "Sign In",
    logout: "Logout",
    selectRole: "Please select a role",
    backToLogin: "Back to Login",
    passwordsDontMatch: "Passwords don't match",
    invalidEmail: "Please enter a valid email",
    eventHost: "Event Host",
    eventGoer: "Event Goer",
    copyright: "2025 RwandaConnect."
  },
  sw: {
    welcomeShort: "Karibu RwandaConnect – mwongozo wako wa matukio yote Rwanda!",
    home: "ukurasa wa nyumbani",
    cities: "Miji",
    map: "Ramani",
    login: "Ingia / Jiandikishe",
    city1: "Kigali", 
    desc1: "Kigali ni mji mkuu, umejaa maisha, matukio na utamaduni.",
    city2: "Nyagatare", 
    desc2: "Inajulikana kwa joto lake na ukuaji wa matukio.",
    city3: "Rubavu", 
    desc3: "Mji mzuri kando ya ziwa, bora kwa muziki na matukio ya pwani.",
    city4: "Rwamagana", 
    desc4: "Mji tulivu na wa kirafiki wenye mikutano ya jamii.",
    city5: "Rusizi", 
    desc5: "Maarufu kwa asili yake na matukio ya amani.",
    city6: "Huye", 
    desc6: "Nyumba ya historia na sherehe za kitamaduni.",
    city7: "Musanze", 
    desc7: "Kipenyo cha volkano, kimejaa watalii na matukio.",
    city8: "Bugesera", 
    desc8: "Mji unaokua na idadi inayoongezeka ya matukio ya ndani na historia maalum",
    viewMap: "Tazama Ramani",
    signupAsHost: "Jiandikishe kama Mwenyeji",
    signupAsGoer: "Jiandikishe kama Mgeni",
    alreadyAccount: "Una akaunti tayari?",
    noAccount: "Huna akaunti?",
    signupFree: "Jiandikishe kwa bure!",
    or: "au",
    fieldRequired: "Hii sehemu inahitajika",
    fullName: "Jina Kamili",
    email: "Barua Pepe",
    password: "Neno la Siri",
    confirmPassword: "Thibitisha Neno la Siri",
    username: "Jina la Mtumiaji",
    organizationName: "Jina la Shirika",
    interests: "Nia",
    hostingType: "Je, unaliona aina gani ya matukio?",
    loginAsHost: "Ingia kama Mwenyeji wa Matukio",
    loginAsGoer: "Ingia kama Mgeni wa Matukio",
    chooseRole: "Chagua jukumu lako",
    createAccount: "Fanya Akaunti",
    signIn: "Ingia",
    logout: "Toka",
    selectRole: "Tafadhali chagua jukumu",
    backToLogin: "Rudi kwa Kuingia",
    passwordsDontMatch: "Neno la siri halina kufanana",
    invalidEmail: "Tafadhali ingiza barua pepe halisi",
    eventHost: "Mwenyeji wa Matukio",
    eventGoer: "Mgeni wa Matukio",
    copyright: "2025 RwandaConnect."
  },
  rw: {
    welcomeShort: "Murakaza neza kuri RwandaConnect – ahantu hazagufasha kubona ibibera mu Rwanda hose!",
    home: "Ahatangira",
    cities: "Imijyi",
    map: "Ikarita",
    login: "Iyandikishe cyangwa Injira",
    city1: "Kigali",
    desc1: "Umurwa mukuru wuzuye ubuzima, umuco, ibitaramo, n'ibindi byinshi.",
    city2: "Nyagatare",
    desc2: "Umujyi ugira ikirere cyiza, abantu basabana, n'ibikorwa bikura umunsi ku wundi.",
    city3: "Rubavu",
    desc3: "Umujyi mwiza ku nkombe z'ikiyaga, uhorana ibitaramo by'umuziki n'ibikorwa bya siporo.",
    city4: "Rwamagana",
    desc4: "Umujyi utuje kandi wakirana yombi abawugana, ufite ibikorwa bitandukanye byakwitabirwa n'imiryango cyangwa inshuti.",
    city5: "Rusizi",
    desc5: "Umujyi uzwi kubera ubwiza bw'akarere. Ni ahantu nyaburanga hatuje.",
    city6: "Huye",
    desc6: "Umujyi w'amateka, umuco, n'imyidagaduro idasanzwe.",
    city7: "Musanze",
    desc7: "Umuryango wo mu Birunga, wuzuye ba mukerarugendo n'ibyo gukora bishimishije.",
    city8: "Bugesera",
    desc8: "Umujyi uri gutera imbere, ufite amateka yihariye.",
    viewMap: "Reba Ikarita",
    signupAsHost: "Iyandikishe nka nyir'ibirori/ibikorwa",
    signupAsGoer: "Iyandikishe nk'uwitabira ibirori/ibikorwa",
    alreadyAccount: "Ufite konte?",
    noAccount: "Nta konte ufite?",
    signupFree: "Iyandikishe nta kiguzi!",
    or: "cyangwa",
    fieldRequired: "Ano makuru arasabwa",
    fullName: "Izina Ryose",
    email: "Imeyili",
    password: "Ijambo ry'ibanga",
    confirmPassword: "Emeza ijambo ry'ibanga",
    username: "Izina ukoresha",
    organizationName: "Izina rya nyir'ibirori/ibikorwa",
    interests: "Ibyo wifuza gukora",
    hostingType: "Ubwoko bw'ibirori/ibikorwa ukora",
    loginAsHost: "Injira nka nyir'ibirori/ibikorwa",
    loginAsGoer: "Injira nk'uwitabiriye ibirori/ibikorwa",
    chooseRole: "Hitamo icyo ukora",
    createAccount: "Kora Konte",
    signIn: "Injira",
    logout: "Sohoka",
    selectRole: "Hitamo icyo ukora",
    backToLogin: "Garuka kuri Kwinjira",
    passwordsDontMatch: "Injiza ijambo ry'ibanga rya nyayo",
    invalidEmail: "Injiza imeyili ya nyayo",
    eventHost: "Nyir'ibirori/ibikorwa",
    eventGoer: "Uwitabira ibirori/ibikorwa",
    copyright: " 2025 RwandaConnect. "
  },
  fr: {
    welcomeShort: "Bienvenue sur RwandaConnect – votre guide pour tous les événements au Rwanda !",
    home: "Accueil",
    cities: "Villes",
    map: "Carte",
    login: "Connexion / Inscription",
    city1: "Kigali", 
    desc1: "Kigali est la capitale, pleine de vie, d'événements et de culture.",
    city2: "Nyagatare", 
    desc2: "Une ville connue pour son climat chaud et sa scène événementielle croissante.",
    city3: "Rubavu", 
    desc3: "Belle ville au bord du lac, parfaite pour la musique et les activités de plage et sportive.",
    city4: "Rwamagana", 
    desc4: "Ville calme et conviviale avec plusieurs activités familiales & rassemblements communautaires.",
    city5: "Rusizi", 
    desc5: "Une ville célèbre pour sa beauté naturelle. Un endroit calme et paisible.",
    city6: "Huye", 
    desc6: "Ville historique et des festivals culturels.",
    city7: "Musanze", 
    desc7: "La Porte des volcans, animée par le tourisme et différents événements.",
    city8: "Bugesera", 
    desc8: "Ville en développement avec un nombre croissant d'activités locales et une histoire particulière",
    viewMap: "Voir la Carte",
    signupAsHost: "S'inscrire en tant que Hôte",
    signupAsGoer: "S'inscrire en tant que Participant",
    alreadyAccount: "Vous avez déjà un compte ?",
    noAccount: "Vous n'avez pas de compte ?",
    signupFree: "Inscrivez-vous gratuitement !",
    or: "ou",
    fieldRequired: "Ce champ est obligatoire",
    fullName: "Nom Complet",
    email: "Email",
    password: "Mot de Passe",
    confirmPassword: "Confirmer le Mot de Passe",
    username: "Nom d'Utilisateur",
    organizationName: "Nom de l'Organisation",
    interests: "Intérêts",
    hostingType: "Quel type d'événements organisez-vous ?",
    loginAsHost: "Se Connecter en tant qu'Hôte",
    loginAsGoer: "Se Connecter en tant que Participant",
    chooseRole: "Choisissez votre rôle",
    createAccount: "Créer un Compte",
    signIn: "Se Connecter",
    logout: "Déconnexion",
    selectRole: "Veuillez sélectionner un rôle",
    backToLogin: "Retour à la Connexion",
    passwordsDontMatch: "Les mots de passe ne correspondent pas",
    invalidEmail: "Veuillez entrer un email valide",
    eventHost: "Organisateur d'Événements",
    eventGoer: "Participant aux Événements",
    copyright: " 2025 RwandaConnect."
  }
};

function setLanguage(lang) {
  localStorage.setItem('selectedLanguage', lang);
  document.documentElement.lang = lang;
  
  document.querySelectorAll('[data-translate]').forEach(el => {
    const key = el.getAttribute('data-translate');
    if (translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });

  document.querySelectorAll('[data-translate-placeholder]').forEach(el => {
    const key = el.getAttribute('data-translate-placeholder');
    if (translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  document.querySelectorAll('[data-translate-value]').forEach(el => {
    const key = el.getAttribute('data-translate-value');
    if (translations[lang][key]) {
      el.value = translations[lang][key];
    }
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('selectedLanguage') || 'en';
  setLanguage(savedLang);
  const selector = document.getElementById('language-selector');
  if (selector) {
    selector.value = savedLang;
    selector.addEventListener('change', e => setLanguage(e.target.value));
  }
});